export interface ProductModel {
  codeProduct: string,
  codpro_b?: string,
  idticket?: string,
  nameProduct: string,
  nompro_b?: string,
  descrProduct?: string,
  img_prod: string,
  img_prod1?: string,
  img_prod2?: string,
  img_prod3?: string,
  totalValue: string,
  porcDescuento?: string,
  color_champions?: string,
  precioSinDcto?: string,
  category?: string,
  subcategory?: string,
  isGold?: boolean,
  cant_nort?: string,
  cant_sur?: string,
  proveedor?: string,
  providerProduct?: string,
  cantidadCart?: number,
  cantidadMeta?: number,
  cantidad?: number,
  palabrasClaves?: string,
}
