export interface StoreModel {
  codcli_b: string,
  nomcli_b: string,
  ape1cli_b?: string,
  ape2cli_b?: string,
  empcli_b?: string,
  telcli_b?: string,
  emacli_b?: string,
  dircli_b?: string,
  estped_b?: string,
  ruta?: string,
  idpedido?: string,
  color?: string,
  meta?: string,
  latcli_b?: string,
  loncli_b?: string,
  ndicli_b?: string,
  ultimacompra?: string,
  skuMeta?: string,
  barcli_b?: string
  ciudad?: string,
  tipoPG?: string,
  encuesta?: string,
}
